### ISSUE TITLE
Not an issue, you can close this once you read it

### ISSUE THREAD

**Issue by ixmatus** [norton/lets#14]
I'm leaving this here to thank you. I needed a LevelDB backend for something and Basho's leveldb fork is too highly optimized to run in an ARM environment and your library has come to the rescue. Please don't adopt `eleveldb`!!!

**Comment by norton** [comment]
Roger!  You are welcome.  How is the library working for you?

**Comment by ixmatus** [comment]
It's working well, there are a few warts here and there - issues I've fixed
that I will push back upstream, but it's a solid library so far. Thank you
for having written it :)
ᐧ

On Wed, Sep 30, 2015 at 7:02 PM, Joseph Wayne Norton <
notifications@github.com> wrote:

> Roger! You are welcome. How is the library working for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/norton/lets/issues/14#issuecomment-144578035>.
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by norton** [comment]
Great.  Thank you for the report.
